#!/usr/bin/env python3
"""Build the index page and gather the study reports into docs/.

Everything this reads comes from `studies/*/study.json`, one file per study
directory, so adding a study means dropping the directory in and running this.
Nothing here imports anything a study needs -- the standard library only -- so
it runs in any interpreter, including one that has never heard of RDKit.

    python site/build_site.py            # rebuild docs/
    python site/build_site.py --check    # report what is stale, change nothing

What it writes:

    docs/index.html              the overall report, one card per study report
    docs/reports/<slug>.html     each study's own report, copied from its results/
    docs/.nojekyll               so GitHub Pages serves the files as they are
    README.md                    the card block between the STUDIES markers

A study's report is built inside its own directory by its own builder, in the
environment that study needs. This only copies the finished page across, and
says so when a study's copy in docs/ is older than the one in its results/.
"""

from __future__ import annotations

import argparse
import html
import json
import shutil
import sys
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from style import CSS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
STUDY_DIR = ROOT / "studies"
DOCS = ROOT / "docs"
REPORT_DIR = DOCS / "reports"
README = ROOT / "README.md"

BEGIN = "<!-- STUDIES:BEGIN -- generated by site/build_site.py, do not edit by hand -->"
END = "<!-- STUDIES:END -->"

REQUIRED_STUDY = ("slug", "reports")
REQUIRED_REPORT = ("slug", "title", "question", "summary", "finding", "source")


# --------------------------------------------------------------- the registry
@dataclass
class Report:
    """One card, and one page under docs/reports/."""

    slug: str
    title: str
    question: str
    summary: str
    finding: str
    source: str
    study: "Study" = field(repr=False, default=None)
    eyebrow: str = ""
    caveat: str = ""
    builder: str = ""
    facts: list = field(default_factory=list)
    validates: list = field(default_factory=list)

    @property
    def source_path(self) -> Path:
        return self.study.path / self.source

    @property
    def docs_path(self) -> Path:
        return REPORT_DIR / f"{self.slug}.html"

    @property
    def href(self) -> str:
        return f"reports/{self.slug}.html"


@dataclass
class Study:
    """One directory under studies/, holding one or more reports."""

    path: Path
    slug: str
    name: str = ""
    order: int = 999
    datasets: list = field(default_factory=list)
    endpoints: int = 0
    protocol: str = ""
    updated: str = ""
    reports: list = field(default_factory=list)

    @property
    def rel(self) -> str:
        return f"studies/{self.path.name}"


def load_studies() -> list[Study]:
    """Every study.json under studies/, by `order` and then by slug.

    A study without an `order` sorts after every study that has one, so a new
    directory can be dropped in without renumbering the others.
    """
    studies = []
    for path in sorted(STUDY_DIR.glob("*/study.json")):
        raw = json.loads(path.read_text(encoding="utf-8"))
        missing = [k for k in REQUIRED_STUDY if k not in raw]
        if missing:
            raise SystemExit(f"{path}: missing {', '.join(missing)}")
        reports = raw.pop("reports")
        study = Study(path=path.parent, **{k: v for k, v in raw.items()
                                           if k in Study.__annotations__})
        for entry in reports:
            missing = [k for k in REQUIRED_REPORT if k not in entry]
            if missing:
                raise SystemExit(f"{path}: report is missing {', '.join(missing)}")
            fields = {k: v for k, v in entry.items() if k in Report.__annotations__}
            study.reports.append(Report(study=study, **fields))
        if not study.name:
            study.name = study.slug
        studies.append(study)
    if not studies:
        raise SystemExit(f"no study.json found under {STUDY_DIR}")
    studies.sort(key=lambda s: (s.order, s.slug))
    return studies


def all_reports(studies) -> list[Report]:
    return [report for study in studies for report in study.reports]


# ------------------------------------------------------------- copying pages
def gather_reports(studies, check: bool) -> list[str]:
    """Bring each study's built report into docs/reports/. Returns any notes."""
    notes = []
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    for report in all_reports(studies):
        src, dst = report.source_path, report.docs_path
        if not src.exists():
            if dst.exists():
                notes.append(f"{report.slug}: no {report.study.rel}/{report.source}, "
                             f"keeping the copy already in docs/")
            else:
                notes.append(f"{report.slug}: MISSING -- neither "
                             f"{report.study.rel}/{report.source} nor {dst.relative_to(ROOT)}")
            continue
        if dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime:
            continue
        if check:
            notes.append(f"{report.slug}: docs/ copy is stale")
            continue
        shutil.copy2(src, dst)
        notes.append(f"{report.slug}: copied ({src.stat().st_size / 1e6:.1f} MB)")
    return notes


# ------------------------------------------------------------------ the page
def e(text: str) -> str:
    return html.escape(str(text), quote=False)


def fact_block(facts, css_class="facts") -> str:
    if not facts:
        return ""
    cells = "".join(
        f'<div class="fact"><b>{e(f["n"])}</b><span>{e(f["label"])}</span></div>'
        for f in facts
    )
    return f'<div class="{css_class}">{cells}</div>'


def card(report: Report) -> str:
    study = report.study
    eyebrow = " · ".join(x for x in (report.eyebrow, ", ".join(study.datasets)) if x)
    parts = [
        f'<p class="eyebrow">{e(eyebrow)}</p>',
        f'<h3><a href="{report.href}">{e(report.title)}</a></h3>',
        f'<p class="q">{e(report.question)}</p>',
        f"<p>{e(report.summary)}</p>",
        f'<p class="finding">{e(report.finding)}</p>',
    ]
    if report.validates:
        links = ", ".join(f'<a href="{v["url"]}">{e(v["name"])}</a>' for v in report.validates)
        parts.append(f'<p class="validates">Puts to the test: {links}</p>')
    if report.caveat:
        parts.append(f'<p class="caveat">{e(report.caveat)}</p>')
    parts.append(fact_block(report.facts, "cardfacts"))
    parts.append(
        '<p class="meta">'
        f'<a class="go" href="{report.href}">Read the report →</a>'
        '<span class="sep">|</span>'
        f'<a href="https://github.com/PatWalters/model-validation-central/tree/main/{study.rel}">'
        f"{e(study.name)}</a>"
        + (f'<span class="sep">|</span><span>{e(study.updated)}</span>' if study.updated else "")
        + "</p>"
    )
    return '<article class="card">' + "".join(parts) + "</article>"


def summary_facts(studies) -> list[dict]:
    reports = all_reports(studies)
    methods = {v["name"] for r in reports for v in r.validates}
    datasets = {d for s in studies for d in s.datasets}
    endpoints = max((s.endpoints for s in studies), default=0)
    return [
        {"n": str(len(studies)), "label": "studies"},
        {"n": str(len(reports)), "label": "reports"},
        {"n": str(len(methods)), "label": "published methods"},
        {"n": str(endpoints), "label": "endpoints"},
        {"n": str(len(datasets)), "label": "data sets"},
    ]


def render_index(studies) -> str:
    cards = "".join(card(r) for r in all_reports(studies))
    protocols = sorted({s.protocol for s in studies if s.protocol})
    shared = (
        "<p>Every study here is scored the same way, which is what makes the cards "
        "comparable rather than merely adjacent. Molecules are clustered, a fixed "
        "fraction is held out once, and the 25 replicates come from five repeats of a "
        "five-fold <code>GroupKFold</code> over the clusters in what remains. Every "
        "method sees identical training molecules in every fold and is scored on the "
        "same untouched test set, so a difference in the metrics is a difference in the "
        "method.</p>"
        "<p>The statistics follow the protocol of Ash et al. and "
        '<a href="https://practicalcheminformatics.blogspot.com/2025/03/even-more-thoughts-on-ml-method.html">'
        "Even More Thoughts on ML Method Comparisons</a>: distributions over folds, "
        "corrected for multiple comparisons, and no bold maxima. Where two methods "
        "cannot be separated, both are reported as tied.</p>"
        "<p>Everything is run on two unrelated data sets. A comparison run once is a "
        "hypothesis, and the interesting question about any result below is which half "
        "of it replicates.</p>"
    )
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Model Validation Central</title>
<meta name="description" content="Published molecular machine learning methods, re-run on the same molecules, the same folds and the same statistics.">
<style>{CSS}</style>
</head>
<body>
<main class="wrap">
  <p class="eyebrow">Practical Cheminformatics</p>
  <h1>Model Validation Central</h1>
  <p class="lede">Published machine learning methods for molecular property prediction,
  re-run on the same molecules, the same folds and the same statistics, so their claims
  can be read against one another instead of against whatever each paper chose to
  compare itself with.</p>
  {fact_block(summary_facts(studies))}

  <h2>What makes these comparable</h2>
  {shared}

  <h2>The studies</h2>
  <div class="cards bleed">{cards}</div>

  <hr class="rule">
  <p class="footnote">Each card links to that study's full report and to the code that
  produced it. Every study directory carries its own README, its own requirements, and
  the per-fold metrics behind its figures, so any of them can be rebuilt on its own.
  Source at
  <a href="https://github.com/PatWalters/model-validation-central">PatWalters/model-validation-central</a>.
  Built {date.today().isoformat()}.</p>
</main>
</body>
</html>
"""


# ---------------------------------------------------------------- the README
def render_readme_block(studies) -> str:
    lines = []
    for study in studies:
        for report in study.reports:
            lines.append(f"### [{report.title}](docs/reports/{report.slug}.html)")
            lines.append("")
            lines.append(f"*{report.question}*")
            lines.append("")
            lines.append(report.summary)
            lines.append("")
            lines.append(f"> **What came out.** {report.finding}")
            lines.append("")
            if report.validates:
                links = ", ".join(f"[{v['name']}]({v['url']})" for v in report.validates)
                lines.append(f"Puts to the test: {links}")
                lines.append("")
            if report.caveat:
                lines.append(f"*{report.caveat}*")
                lines.append("")
            facts = " · ".join(f"{f['n']} {f['label']}" for f in report.facts)
            code = f"[`{study.rel}`]({study.rel}/)"
            lines.append(f"{facts}  \nCode: {code}"
                         + (f" · Report builder: `{report.builder}`" if report.builder else ""))
            lines.append("")
    return "\n".join(lines).rstrip()


def update_readme(studies, check: bool) -> str | None:
    if not README.exists():
        return "README.md not found, skipped"
    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        return f"README.md has no {BEGIN.split()[1]} markers, skipped"
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = f"{head}{BEGIN}\n\n{render_readme_block(studies)}\n\n{END}{tail}"
    if new == text:
        return None
    if check:
        return "README.md card block is stale"
    README.write_text(new, encoding="utf-8")
    return "README.md card block rewritten"


# ------------------------------------------------------------------- driver
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="report what would change and write nothing")
    args = ap.parse_args()

    studies = load_studies()
    reports = all_reports(studies)
    print(f"{len(studies)} studies, {len(reports)} reports")

    notes = gather_reports(studies, args.check)

    index = render_index(studies)
    if args.check:
        current = (DOCS / "index.html").read_text(encoding="utf-8") if (DOCS / "index.html").exists() else ""
        # the build date changes every day and is not a reason to call the page stale
        if current.split("Built ")[0] != index.split("Built ")[0]:
            notes.append("docs/index.html is stale")
    else:
        DOCS.mkdir(parents=True, exist_ok=True)
        (DOCS / "index.html").write_text(index, encoding="utf-8")
        (DOCS / ".nojekyll").write_text("")
        notes.append(f"docs/index.html written ({len(index) / 1e3:.0f} kB)")

    note = update_readme(studies, args.check)
    if note:
        notes.append(note)

    for line in notes:
        print(" ", line)
    if args.check and any("stale" in n or "MISSING" in n for n in notes):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
