#!/usr/bin/env python3
"""Build the index page and gather the study reports into docs/.

Everything this reads comes from `studies/*/study.json`, one file per study
directory, so adding a study means dropping the directory in and running this.
Nothing here imports anything a study needs -- the standard library only -- so
it runs in any interpreter, including one that has never heard of RDKit.

    python site/build_site.py            # rebuild docs/
    python site/build_site.py --check    # report what is stale, change nothing

What it writes:

    docs/index.html              the overall report, one card per study report
    docs/reports/<slug>.html     each study's own report, copied from its results/
    docs/.nojekyll               so GitHub Pages serves the files as they are
    README.md                    the card block between the STUDIES markers

A study's report is built inside its own directory by its own builder, in the
environment that study needs. This only copies the finished page across, and
says so when a study's copy in docs/ is older than the one in its results/.
"""

from __future__ import annotations

import argparse
import html
import json
import shutil
import sys
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from style import CSS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
STUDY_DIR = ROOT / "studies"
DOCS = ROOT / "docs"
REPORT_DIR = DOCS / "reports"
README = ROOT / "README.md"

# GitHub renders a link to a .html file in the tree as its source, not as the
# page, so the README links at the published copies instead of at docs/.
REPO = "https://github.com/PatWalters/model-validation-central"
SITE = "https://patwalters.github.io/model-validation-central"

BEGIN = "<!-- STUDIES:BEGIN -- generated by site/build_site.py, do not edit by hand -->"
END = "<!-- STUDIES:END -->"

REQUIRED_STUDY = ("slug", "reports")
REQUIRED_REPORT = ("slug", "title", "question", "summary", "finding", "source")


# --------------------------------------------------------------- the registry
@dataclass
class Report:
    """One card, and one page under docs/reports/."""

    slug: str
    title: str
    question: str
    summary: str
    finding: str
    source: str
    study: "Study" = field(repr=False, default=None)
    date: str = ""
    eyebrow: str = ""
    caveat: str = ""
    builder: str = ""
    facts: list = field(default_factory=list)
    validates: list = field(default_factory=list)

    @property
    def source_path(self) -> Path:
        return self.study.path / self.source

    @property
    def docs_path(self) -> Path:
        return REPORT_DIR / f"{self.slug}.html"

    @property
    def href(self) -> str:
        return f"reports/{self.slug}.html"

    @property
    def when(self) -> str:
        """The date to sort and label by, falling back to the study's."""
        return self.date or self.study.updated


@dataclass
class Study:
    """One directory under studies/, holding one or more reports."""

    path: Path
    slug: str
    name: str = ""
    datasets: list = field(default_factory=list)
    endpoints: int = 0
    protocol: str = ""
    updated: str = ""
    reports: list = field(default_factory=list)

    @property
    def rel(self) -> str:
        return f"studies/{self.path.name}"


def load_studies() -> list[Study]:
    """Every study.json under studies/, by slug.

    This is only the load order. What the page and the README are ordered by is
    `all_reports`, newest report first.
    """
    studies = []
    for path in sorted(STUDY_DIR.glob("*/study.json")):
        raw = json.loads(path.read_text(encoding="utf-8"))
        missing = [k for k in REQUIRED_STUDY if k not in raw]
        if missing:
            raise SystemExit(f"{path}: missing {', '.join(missing)}")
        reports = raw.pop("reports")
        study = Study(path=path.parent, **{k: v for k, v in raw.items()
                                           if k in Study.__annotations__})
        for entry in reports:
            missing = [k for k in REQUIRED_REPORT if k not in entry]
            if missing:
                raise SystemExit(f"{path}: report is missing {', '.join(missing)}")
            fields = {k: v for k, v in entry.items() if k in Report.__annotations__}
            study.reports.append(Report(study=study, **fields))
        if not study.name:
            study.name = study.slug
        studies.append(study)
    if not studies:
        raise SystemExit(f"no study.json found under {STUDY_DIR}")
    studies.sort(key=lambda s: s.slug)
    return studies


def all_reports(studies) -> list[Report]:
    """Every report, newest study first, with a study's own reports kept together.

    A study is placed by its newest report, and its reports then run newest
    first within that block. So a study added later arrives at the top without
    anything being renumbered, and the two reports that come out of
    expansion-ml-comparison still sit next to each other even though they were
    built eight days apart.

    A report with no date sorts last rather than crashing the build.
    """
    def newest(study) -> str:
        return max((r.when or "" for r in study.reports), default="")

    ordered = []
    for study in sorted(studies, key=lambda s: (newest(s), s.slug), reverse=True):
        # Two passes rather than one reversed key: `reverse=True` would flip the
        # tiebreak as well, ordering same-day reports by slug backwards.
        reports = sorted(study.reports, key=lambda r: r.slug)
        reports.sort(key=lambda r: r.when or "", reverse=True)
        ordered.extend(reports)
    return ordered


# ------------------------------------------------------------- copying pages
def gather_reports(studies, check: bool) -> list[str]:
    """Bring each study's built report into docs/reports/. Returns any notes."""
    notes = []
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    for report in all_reports(studies):
        src, dst = report.source_path, report.docs_path
        if not src.exists():
            if dst.exists():
                notes.append(f"{report.slug}: no {report.study.rel}/{report.source}, "
                             f"keeping the copy already in docs/")
            else:
                notes.append(f"{report.slug}: MISSING -- neither "
                             f"{report.study.rel}/{report.source} nor {dst.relative_to(ROOT)}")
            continue
        if dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime:
            continue
        if check:
            notes.append(f"{report.slug}: docs/ copy is stale")
            continue
        shutil.copy2(src, dst)
        notes.append(f"{report.slug}: copied ({src.stat().st_size / 1e6:.1f} MB)")
    return notes


# ------------------------------------------------------------------ the page
def e(text: str) -> str:
    return html.escape(str(text), quote=False)


def fact_block(facts, css_class="facts") -> str:
    if not facts:
        return ""
    cells = "".join(
        f'<div class="fact"><b>{e(f["n"])}</b><span>{e(f["label"])}</span></div>'
        for f in facts
    )
    return f'<div class="{css_class}">{cells}</div>'


def papers_block(papers) -> str:
    """The papers a study puts to the test, cited in full.

    The claim being tested is the point of the card, so the reference is part of
    the argument rather than a footnote to it: title first, then who wrote it and
    where it appeared, and the identifier as the link.
    """
    if not papers:
        return ""
    items = []
    for p in papers:
        title = e(p.get("title", p.get("name", "")))
        line = f'<p class="ptitle">{title}</p>'
        if p.get("authors"):
            line += f'<p class="pauthors">{e(p["authors"])}</p>'
        bits = []
        if p.get("venue"):
            bits.append(f'<span class="pvenue">{e(p["venue"])}</span>')
        if p.get("url"):
            bits.append(f'<a class="pdoi" href="{p["url"]}">{e(p.get("label", p["url"]))}</a>')
        if bits:
            line += '<p class="pwhere">' + " · ".join(bits) + "</p>"
        items.append(f'<li class="paper">{line}</li>')
    label = "The paper put to the test" if len(papers) == 1 else "The papers put to the test"
    return (f'<div class="papers"><p class="plabel">{label}</p>'
            f'<ul class="paperlist">{"".join(items)}</ul></div>')


def references_block(references) -> str:
    """The papers behind the table's rows, numbered by first appearance in it.

    A row names a published method, and the citation is what lets a reader go and
    check it, so the numbers live in the table and the list sits directly under
    it rather than at the bottom of the page.
    """
    if not references:
        return ""
    items = "".join(
        f'<li id="ovref-{r["n"]}">{e(r["authors"])} <b>{e(r["title"])}.</b> '
        f'<span class="venue">{e(r["venue"])}.</span> '
        f'<a href="{r["url"]}">{e(r["label"])}</a></li>'
        for r in references
    )
    return ('<div class="refsblock"><p class="eyebrow">The methods in print</p>'
            f'<ol class="refs">{items}</ol></div>')


def overview_block() -> str:
    """The cross-study comparison, from what `site/overview.py` left behind.

    Absent that file the page simply goes without it, so the index still builds
    in an interpreter that has never seen pandas.
    """
    path = DOCS / "overview.json"
    if not path.exists():
        return ""
    d = json.loads(path.read_text(encoding="utf-8"))
    sets = d["datasets"]
    keys = list(sets)
    metric = d.get("metric", "r2")
    label = d.get("metric_label", "R²")

    head = (
        "<tr><th scope='col'></th><th scope='col'>From</th>"
        + "".join(f"<th scope='col' colspan='3'>{e(sets[k]['label'])}, "
                  f"of {sets[k]['combinations']} endpoints</th>" for k in keys)
        + "</tr><tr><th></th><th></th>"
        + "".join("<th>best alone</th><th>tied</th><th>worse</th>" for _ in keys)
        + "</tr>"
    )
    rows = []
    for m in d["methods"]:
        marks = ""
        if m.get("refs"):
            links = ", ".join(f'<a href="#ovref-{n}">{n}</a>' for n in m["refs"])
            marks = f'<sup class="ref">{links}</sup>'
        cells = [
            f'<th scope="row"><span class="swatch" style="background:{m["color"]}"></span>'
            f'{e(m["label"])}{marks}</th>',
            f'<td class="from">{e(m["study"])}</td>',
        ]
        for k in keys:
            c = m["counts"][k]
            for kind in ("alone", "tied", "worse"):
                n = c[kind]
                cls = "num zero" if n == 0 else "num"
                cells.append(f'<td class="{cls}">{n}</td>')
        rows.append("<tr>" + "".join(cells) + "</tr>")

    figures = "".join(
        f'<figure class="overfig"><img src="{sets[k]["figure"]}" '
        f'alt="Tukey HSD on {e(label)}, {e(sets[k]["label"])}, one panel per endpoint">'
        f'<figcaption>{e(sets[k]["label"])}: one panel per endpoint, Tukey HSD on {e(label)} '
        f'over the {sets[k]["folds_per_method"] // sets[k]["endpoints"]} folds. Blue is the '
        f'best mean, grey cannot be separated from it, red is significantly worse.</figcaption>'
        "</figure>"
        for k in keys
    )
    # MAE is in the units of the endpoint, which the panels' shared axis invites a
    # reader to forget, and on ExpansionRx those units are a log transform with an
    # offset. Both are worth saying where the figure is rather than in a study README.
    caveat = ""
    if metric == "mae":
        caveat = (
            '<p class="footnote">Lower is better, and the panels share an axis so a '
            "difference is the same length everywhere. Read down a panel rather than "
            "across them: MAE carries the units of its endpoint, and the endpoints "
            "differ in how hard they are. On ExpansionRx they are also on a "
            "<code>log10(x + 1)</code> scale, which is nearly linear below x = 1, so an "
            "MAE there is not a clean fold-error — every method shares the target, so "
            "the comparison holds, but the number does not convert. The Biogen "
            "endpoints arrive log-transformed at source.</p>"
        )

    return (
        '<h2 id="overview">Every method, on the same folds</h2>'
        "<p>The studies share their folds, and the four reference arms are copied "
        "between them rather than refit, so their per-fold numbers are identical to "
        "the last bit. That is checked before anything is pooled, and it means every "
        "method below can go into one comparison — which is the whole reason for "
        "collecting them.</p>"
        f"<p>One Tukey HSD per endpoint, over the 25 folds, on {e(label)} — the same "
        "metric the panels below draw, so a row and its panel can never disagree "
        "about who won. A method counts as being on top whenever the correction "
        "cannot separate it from the leading mean, so an endpoint with several "
        "methods on top gives <b>each of them a tie</b> rather than crowning "
        "whichever had the better mean. Only an endpoint with exactly one method on "
        "top awards a <b>best alone</b>. There are no bold maxima.</p>"
        f'<div class="tablewrap bleed"><table class="overview">{head}{"".join(rows)}</table></div>'
        + references_block(d.get("references", []))
        + '<p class="footnote">multimodal-fusion\'s 33 configurations would swamp a '
        "ten-way comparison and widen the correction for everyone, so it is "
        "represented by one cell of its grid chosen in advance rather than on the "
        "results: all four modalities, early fusion, LightGBM. Its own report ranks "
        "the whole grid. Counts here are also stricter than the ones in the "
        "individual reports: Tukey's correction widens with the number of methods, so "
        "pooling ten of them turns some outright wins into ties.</p>"
        f'<div class="bleed">{figures}</div>'
        + caveat
    )


def card(report: Report) -> str:
    study = report.study
    eyebrow = " · ".join(x for x in (report.eyebrow, ", ".join(study.datasets)) if x)
    parts = [
        f'<p class="eyebrow">{e(eyebrow)}</p>',
        f'<h3><a href="{report.href}">{e(report.title)}</a></h3>',
        f'<p class="q">{e(report.question)}</p>',
        # The paper is what the study is about, so it is cited before the study
        # is described rather than after it.
        papers_block(report.validates),
        f"<p>{e(report.summary)}</p>",
        f'<p class="finding">{e(report.finding)}</p>',
    ]
    if report.caveat:
        parts.append(f'<p class="caveat">{e(report.caveat)}</p>')
    parts.append(fact_block(report.facts, "cardfacts"))
    parts.append(
        '<p class="meta">'
        f'<a class="go" href="{report.href}">Read the report →</a>'
        '<span class="sep">|</span>'
        f'<a href="{REPO}/tree/main/{study.rel}">'
        f"{e(study.name)}</a>"
        + (f'<span class="sep">|</span><span>{e(report.when)}</span>' if report.when else "")
        + "</p>"
    )
    return '<article class="card">' + "".join(parts) + "</article>"


def summary_facts(studies) -> list[dict]:
    reports = all_reports(studies)
    methods = {v["name"] for r in reports for v in r.validates}
    datasets = {d for s in studies for d in s.datasets}
    endpoints = max((s.endpoints for s in studies), default=0)
    return [
        {"n": str(len(studies)), "label": "studies"},
        {"n": str(len(reports)), "label": "reports"},
        {"n": str(len(methods)), "label": "published methods"},
        {"n": str(endpoints), "label": "endpoints"},
        {"n": str(len(datasets)), "label": "data sets"},
    ]


def render_index(studies) -> str:
    cards = "".join(card(r) for r in all_reports(studies))
    protocols = sorted({s.protocol for s in studies if s.protocol})
    shared = (
        "<p>Every study here is scored the same way, which is what makes the cards "
        "comparable rather than merely adjacent. Molecules are clustered, a fixed "
        "fraction is held out once, and the 25 replicates come from five repeats of a "
        "five-fold <code>GroupKFold</code> over the clusters in what remains. Every "
        "method sees identical training molecules in every fold and is scored on the "
        "same untouched test set, so a difference in the metrics is a difference in the "
        "method.</p>"
        "<p>The statistics follow the protocol of Ash et al. and "
        '<a href="https://practicalcheminformatics.blogspot.com/2025/03/even-more-thoughts-on-ml-method.html">'
        "Even More Thoughts on ML Method Comparisons</a>: distributions over folds, "
        "corrected for multiple comparisons, and no bold maxima. Where two methods "
        "cannot be separated, both are reported as tied.</p>"
        "<p>Everything is run on two unrelated data sets. A comparison run once is a "
        "hypothesis, and the interesting question about any result below is which half "
        "of it replicates.</p>"
    )
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Model Validation Central</title>
<meta name="description" content="Published molecular machine learning methods, re-run on the same molecules, the same folds and the same statistics.">
<style>{CSS}</style>
</head>
<body>
<main class="wrap">
  <p class="eyebrow">Practical Cheminformatics</p>
  <h1>Model Validation Central</h1>
  <p class="lede">Published machine learning methods for molecular property prediction,
  re-run on the same molecules, the same folds and the same statistics, so their claims
  can be read against one another instead of against whatever each paper chose to
  compare itself with.</p>
  {fact_block(summary_facts(studies))}

  {overview_block()}

  <h2>What makes these comparable</h2>
  {shared}

  <h2>The studies</h2>
  <div class="cards bleed">{cards}</div>

  <hr class="rule">
  <p class="footnote">Each card links to that study's full report and to the code that
  produced it. Every study directory carries its own README, its own requirements, and
  the per-fold metrics behind its figures, so any of them can be rebuilt on its own.
  Source at
  <a href="{REPO}">PatWalters/model-validation-central</a>.
  Built {date.today().isoformat()}.</p>
</main>
</body>
</html>
"""


# ---------------------------------------------------------------- the README
def render_readme_block(studies) -> str:
    """The card block for the README, in the same order as the index page."""
    lines = []
    for report in all_reports(studies):
        study = report.study
        lines.append(f"### [{report.title}]({SITE}/reports/{report.slug}.html)")
        lines.append("")
        lines.append(f"*{report.question}*")
        lines.append("")
        lines.append(report.summary)
        lines.append("")
        lines.append(f"> **What came out.** {report.finding}")
        lines.append("")
        if report.validates:
            lines.append("**Puts to the test**")
            lines.append("")
            for p in report.validates:
                cite = f"**{p.get('title', p.get('name'))}.**"
                if p.get("authors"):
                    cite = f"{p['authors']} {cite}"
                if p.get("venue"):
                    cite += f" *{p['venue']}.*"
                if p.get("url"):
                    cite += f" [{p.get('label', p['url'])}]({p['url']})"
                lines.append(f"- {cite}")
            lines.append("")
        if report.caveat:
            lines.append(f"*{report.caveat}*")
            lines.append("")
        facts = " · ".join(f"{f['n']} {f['label']}" for f in report.facts)
        code = f"[`{study.rel}`]({study.rel}/)"
        lines.append(f"{facts}  \nCode: {code}"
                     + (f" · Report builder: `{report.builder}`" if report.builder else ""))
        lines.append("")
    return "\n".join(lines).rstrip()


def update_readme(studies, check: bool) -> str | None:
    if not README.exists():
        return "README.md not found, skipped"
    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        return f"README.md has no {BEGIN.split()[1]} markers, skipped"
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = f"{head}{BEGIN}\n\n{render_readme_block(studies)}\n\n{END}{tail}"
    if new == text:
        return None
    if check:
        return "README.md card block is stale"
    README.write_text(new, encoding="utf-8")
    return "README.md card block rewritten"


# ------------------------------------------------------------------- driver
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="report what would change and write nothing")
    args = ap.parse_args()

    studies = load_studies()
    reports = all_reports(studies)
    print(f"{len(studies)} studies, {len(reports)} reports")

    notes = gather_reports(studies, args.check)

    index = render_index(studies)
    if args.check:
        current = (DOCS / "index.html").read_text(encoding="utf-8") if (DOCS / "index.html").exists() else ""
        # the build date changes every day and is not a reason to call the page stale
        if current.split("Built ")[0] != index.split("Built ")[0]:
            notes.append("docs/index.html is stale")
    else:
        DOCS.mkdir(parents=True, exist_ok=True)
        (DOCS / "index.html").write_text(index, encoding="utf-8")
        (DOCS / ".nojekyll").write_text("")
        notes.append(f"docs/index.html written ({len(index) / 1e3:.0f} kB)")

    note = update_readme(studies, args.check)
    if note:
        notes.append(note)

    for line in notes:
        print(" ", line)
    if args.check and any("stale" in n or "MISSING" in n for n in notes):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
